"""Add max_widgets to Website

Revision ID: 18c5b8a4bb19
Revises: 4ae168b0245d
Create Date: 2026-01-12 15:43:11.304305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18c5b8a4bb19'
down_revision = '4ae168b0245d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('website', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_widgets', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('website', schema=None) as batch_op:
        batch_op.drop_column('max_widgets')

    # ### end Alembic commands ###
