"""add website public_key

Revision ID: 4ae168b0245d
Revises: b99f73895d52
Create Date: 2026-01-08 17:38:15.475290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ae168b0245d'
down_revision = 'b99f73895d52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('website', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_key', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_website_public_key'), ['public_key'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('website', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_website_public_key'))
        batch_op.drop_column('public_key')

    # ### end Alembic commands ###
